### ISSUE TITLE
Window won't close if not active on Windows (Win32)

### ISSUE THREAD

**Issue by cnihelton** [zonble/flutter_window_close#1]
Hello!

I noticed an unexpected behavior on your plugin while I was doing some research about window management on Flutter for Desktop: the window will not close if it's not active. That's due the call for `GetActiveWindow()` in the method call handler:
https://github.com/zonble/flutter_window_close/blob/ce5348342e6c6a29abe084510109e7e4f78f36ec/windows/flutter_window_close_plugin.cpp#L72-L87

I tested Linux as well, only Windows showed that behavior. I couldn't test MacOS.

A motivating use case would be prompting the user before closing the window but having a timeout for its reaction. The clip below illustrates that idea and shows how the window won't close after the timeout (5s) if the user is interacting with other window at that moment. Just two additions to your `example/lib/main.dart` will reproduce the scenario shown in the videoclip.

```diff
diff --git a/example/lib/main.dart b/example/lib/main.dart
index 6741910..17fd6bf 100644
--- a/example/lib/main.dart
+++ b/example/lib/main.dart
@@ -75,6 +75,7 @@ class _MainPageState extends State<MainPage> {
             builder: (context) {
               return AlertDialog(
                   title: const Text('Do you really want to quit?'),
+                  content: const Text('This will close in a few seconds if you do not hit the "No" button.'),
                   actions: [
                     ElevatedButton(
                         onPressed: () {
@@ -89,7 +90,7 @@ class _MainPageState extends State<MainPage> {
                         },
                         child: const Text('No'))
                   ]);
-            });
+            }).timeout(const Duration(seconds: 5), onTimeout: () => true);
       } else if (_index == 1) {
         final result = await FlutterPlatformAlert.showCustomAlert(
           windowTitle: "Really?",
```

https://user-images.githubusercontent.com/11138291/154739322-7049bf2b-59ab-4f2d-8feb-3132d7047e3e.mp4

I forked your plugin and experimented a fix, should you be interested in it I can open a PR. The idea is basically never call `GetActiveWindow()`, use the Flutter API to register a WindProc delegate and finally, at the moment of the method call, get the parent window of the Flutter view, which can be made accessible by storing a pointer to the Registrar (most plugins do that). With that in place, even if the window is minimized it will exit after the timeout.

**Comment by zonble** [comment]
Hi!

To be honest I did not imagine the scenario to close the current window after a delay. Thanks for reporting the issue.

This weekend I am traveling without a Windows PC so I cannot do testing until being back. A PR is welcome. Thanks!

**Comment by cnihelton** [comment]
Hi! Sorry for taking too long to respond. I saw you fixed the issue. My approach was quite different because I wanted to avoid calling `GetActiveWindow()`. If you want to compare it to yours, there it is: https://github.com/zonble/flutter_window_close/compare/main...CarlosNihelton:fix-windows-parent?expand=1

Otherwise feel free to disregard.
