### ISSUE TITLE
Does not work on Web.

### ISSUE THREAD

**Issue by hyungtaecf** [zonble/flutter_window_close#10]
On pub.dev it says this package works on the web but throws an error "The method does not work in Flutter Web." at the top of the method "setWindowShouldCloseHandler". Please update the supported platforms removing "web" if it is not ready for the web.

Edit: Sorry, didn't notice the note about the "setWebReturnValue" method. I'm closing this issue.

**Comment by ltOgt** [comment]
For anyone reading this in the future:

note that it might not work in the browser auto-opened for the debug session.

try pasting the link into another browser session during debug, and it should work there.

```dart
 @override
  void initState() {
    super.initState();

    if (kIsWeb) {
      FlutterWindowClose.setWebReturnValue('Are you sure?');
      return;
    }  
}
```
