### ISSUE TITLE
Issue on Linux after a flutter upgrade

### ISSUE THREAD

**Issue by florianguyot** [zonble/flutter_window_close#11]
Hello, 
I am using the package for a desktop app. I tested on linux and it seems that the flutter version `3.16.0` and even previous version (tested also in the `3.13.5`) does not execute the callback. 
It can be reproduced directly in with the example. 

## Linux with flutter 3.16.0 
-> `flutter run -d linux` does not execute the callback when closing the app.
``` 
 flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.16.0, on Fedora Linux 37 (Workstation Edition) 6.5.8-100.fc37.x86_64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (2 available)
[✓] Network resources

• No issues found!
``` 
In the log I can see that something went wrong : 
```
(flutter_window_close_example:270572): Gdk-CRITICAL **: 11:04:02.969: gdk_window_get_state: assertion 'GDK_IS_WINDOW (window)' failed`
```

## Linux with flutter 3.7.8
-> `flutter run -d linux` works just fine

``` 
flutter doctor
Doctor summary (to see all details, run flutter doctor -v):
[✓] Flutter (Channel stable, 3.7.8, on Fedora Linux 37 (Workstation Edition) 6.5.8-100.fc37.x86_64, locale en_US.UTF-8)
[✓] Android toolchain - develop for Android devices (Android SDK version 31.0.0)
[✓] Chrome - develop for the web
[✓] Linux toolchain - develop for Linux desktop
[✓] Android Studio (version 2020.3)
[✓] VS Code (version 1.83.1)
[✓] Connected device (2 available)
[✓] HTTP Host Availability

• No issues found!
```

**Comment by zonble** [comment]
I took a look at the code of Flutter engine. It looks like Flutter itself now connects to the "delete-event" signal and replaces our connections. Let me think if I can find a way to make the plugin to work with newer version of Flutter.

https://github.com/flutter/engine/blob/77432202f766b27b3404b4c324620f8e54699c39/shell/platform/linux/fl_view.cc#L560

**Comment by florianguyot** [comment]
Thanks @zonble , it works like a charm :)
