### ISSUE TITLE
应用退出的处理，而不是窗口关闭

### ISSUE THREAD

**Issue by mapleafgo** [zonble/flutter_window_close#5]
你好，我的应用由于大部分时间存活于后台。我想应用被系统退出时（如由于关机被退出）执行一些释放操作，这样能监听到吗

**Comment by zonble** [comment]
您好：

其實我不太確定具體來說您在做的是怎樣的應用。Flutter 大抵上還是一個 GUI 框架，大概可以預期是一個 GUI app，所以我一開始的預期也就只是攔截視窗被關閉的事件而已。

如果是關機的時候被退出，以 Linux 或 macOS 來說，想像中大概要去攔截 POSIX signal，像是攔截 SIG_KILL，但這個真的超過一開始做這個 plugin 的範圍了。
