### ISSUE TITLE
Windows platform not working

### ISSUE THREAD

**Issue by pushkinman** [zonble/flutter_window_close#9]
I've added the following code to my application

```
@override
  void initState() {
    super.initState();

    if (kIsWeb) {
      FlutterWindowClose.setWebReturnValue('Are you sure?');
      return;
    }

    FlutterWindowClose.setWindowShouldCloseHandler(() async {
      if (_alertShowing) return false;
      _alertShowing = true;

      return await showDialog(
          context: context,
          builder: (context) {
            return AlertDialog(
                title: const Text('Do you really want to quit?'),
                actions: [
                  ElevatedButton(
                      onPressed: () {
                        Navigator.of(context).pop(true);
                        _alertShowing = false;
                      },
                      child: const Text('Yes')),
                  ElevatedButton(
                      onPressed: () {
                        Navigator.of(context).pop(false);
                        _alertShowing = false;
                      },
                      child: const Text('No'))
                ]);
          });
    });
  }
```

This works on macOS, but on not on Windows. When I click exit button on the top right of the window, the application quits right away. 

P.S. I've looked at the example project and it works on Windows, however when I copy the exact same code into a new flutter project it does not work on Windows. I using the latest 0.2.2 version.

**Comment by organic-nailer** [comment]
The package (0.2.2) on pub.dev looks out of date now.

I have a same problem, we will be able to use this package by importing codes from GitHub directly.

```
flutter_window_close:
  git:
    url: https://github.com/zonble/flutter_window_close
```

**Comment by pushkinman** [comment]
I would advice everyone to proceed with this package instead - https://pub.dev/packages/window_manager. It has all the same fuctionality and even more.

**Comment by bahricanyesil** [comment]
@pushkinman I think the package you indicated does not have a close handler for macOS for the default close button.
@organic-nailer I am also experiencing the same problem on Windows. It works without any problem on macOS but it closes directly without executing the handler on Windows for my app. However, it works for the example app you provided when I directly cloned your repo. The interesting thing is the fact that it was working before. Can it be related to updates? Can you please check it?

**Comment by bahricanyesil** [comment]
I'm also using [Flutter Desktop Sleep Package](https://pub.dev/packages/flutter_desktop_sleep). It looks like the problem is related to the combination of these packages. However, the problem only exists on Windows, not macOS. Do you have any suggestions? @zonble

**Comment by bahricanyesil** [comment]
UPDATE:

I downgraded the package version and tested it. The problem does not exist in v0.2.2. It is most probably related to the updates with version 1.0.0. @zonble

**Comment by pushkinman** [comment]
> @pushkinman I think the package you indicated does not have a close handler for macOS for the default close button. @organic-nailer I am also experiencing the same problem on Windows. It works without any problem on macOS but it closes directly without executing the handler on Windows for my app. However, it works for the example app you provided when I directly cloned your repo. The interesting thing is the fact that it was working before. Can it be related to updates? Can you please check it?

I am currently using https://pub.dev/packages/window_manager and everything works correctly on both macOS and Windows platforms.
